name: deploy_on_push

on: 
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_ADDRESS }}
          REMOTE_USER: ${{ secrets.USER_NAME }}
          TARGET: /root/schluesselmomente-cms
          EXCLUDE: /.git/, .gitignore, .github
          SCRIPT_AFTER: |
            cd /root/schluesselmomente-cms
            docker compose up -d --build || exit 1

        
    
      
